# Generated by Django 4.1.3 on 2023-07-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('thirdName', models.CharField(max_length=20)),
                ('contrie', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('bio', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='')),
                ('DateOfBirth', models.DateField()),
                ('club', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
